epochs: 20

report_interval: 100
val_interval: 100
num_val_batches: 32

checkpointing: False

early_stopping: False
patience: 5

data_loaders:
  train:
    split_key: train_idxs
    batch_size: 512
    num_workers: 4
  validation:
    split_key: val_idxs
    batch_size: 512
    num_workers: 4