gpu_list:
    - 0
seed: null
dump_path: './outputs/'
defaults:
    - data: wcte_mue
    - data/dataset: wcte_cnn_mue
    - model: classifier
    - model/feature_extractor: resnet18
    - model/classification_network: resnet
    - engine: classifier
    - tasks/restore_state: restore_state
    - tasks/evaluate: test
    - sampler@tasks.evaluate.data_loaders.test.sampler: subset_sequential
    - _self_
