_target_: watchmal.model.resnet.resnet18
<<<<<<< HEAD
num_input_channels: 38
num_output_channels: 2
=======
num_input_channels: 19
num_output_channels: 4
conv_pad_mode: circular
>>>>>>> 14ed154 (remove unnecessary quotes in config)
